UI Enhancement and Minor Bug Fix
AY2425S1-CS2103-F13-3/tp pull request #151
Opened 2024-11-06 08:44 UTC by jewiteo

closes #144 #150 

Made minor changes to the UI, namely showing what week/period the schedule is currently displaying and stylistic changes.

Fixes bug where associated contacts to meetings were connected by formatting the flowPane.

![image](https://github.com/user-attachments/assets/15e64010-f92e-4dc0-99ae-5931b0d118fc)

2024-11-06 08:50 UTC, tata32000 requested changes

2024-11-06 08:50 UTC, tata32000 commented on src/main/resources/view/WeeklyCalendarPanel.fxml
> +<?import javafx.scene.control.*?>
Should we use wildcard import here?

2024-11-06 09:16 UTC, LimKaiWei commented
for people with long names is it possible to truncate with `...` to fit in calendar card?
![image](https://github.com/user-attachments/assets/0a13f5b1-47a8-4675-9b28-cd698156b844)

2024-11-06 10:22 UTC, jewiteo commented on src/main/resources/view/WeeklyCalendarPanel.fxml
> +<?import javafx.scene.control.*?>
Nope, will explicitly state it. Thanks for the catch

2024-11-06 16:25 UTC, LimKaiWei approved these changes
LGTM

2024-11-07 11:28 UTC, tata32000 requested changes

2024-11-07 11:28 UTC, tata32000 commented on src/main/resources/view/PersonListCard.fxml
> +<?import javafx.geometry.*?>
We shouldn't use wildcard here right?

2024-11-07 11:52 UTC, tata32000 approved these changes

2024-11-07 14:31 UTC, merged