Add schedule commands into help command
AY2425S1-CS2103-F13-3/tp pull request #95
Opened 2024-10-23 12:43 UTC by QuekBingHeng

Add the various implemented schedule commands from v1.2 - v1.4 into the AB3 help command.

2024-10-23 14:33 UTC, LimKaiWei requested changes

2024-10-23 14:33 UTC, LimKaiWei commented on src/main/java/seedu/address/ui/HelpWindow.java
> +            + "\n" + " \n For Schedule: \n"
Include commands for contacts also?

2024-10-24 11:22 UTC, QuekBingHeng commented on src/main/java/seedu/address/ui/HelpWindow.java
> +            + "\n" + " \n For Schedule: \n"
Got it!

2024-10-24 11:25 UTC, LimKaiWei approved these changes
nice

2024-10-24 11:25 UTC, merged